"""add users table and quiz ownership

Revision ID: 50bc66642d2b
Revises: caeec44412bd
Create Date: 2026-09-12 11:01:57.228950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bc66642d2b'
down_revision: Union[str, Sequence[str], None] = 'caeec44412bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # Every quiz and attempt must belong to a user going forward, but any
    # rows that already exist predate authentication entirely and have no
    # user to attribute them to. There is no correct owner to backfill, so
    # rather than leave them permanently orphaned (nullable owner_id
    # forever, None-checks scattered through the app) or invent a
    # placeholder account, this deletes that pre-auth data. This is a
    # deliberate, documented trade-off -- not an oversight -- made when
    # authentication was added after the app already had real usage.
    op.execute("DELETE FROM quiz_attempts")
    op.execute("DELETE FROM quizzes")

    op.add_column('quiz_attempts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('quizzes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_quizzes_url', 'quizzes', type_='unique')
    op.create_index(op.f('ix_quizzes_owner_id'), 'quizzes', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_quizzes_owner_url', 'quizzes', ['owner_id', 'url'])
    op.create_foreign_key(None, 'quizzes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema.

    NOTE: this does not restore quiz/attempt rows deleted during upgrade()
    -- that data is genuinely gone, not just hidden. Downgrading only
    reverses the schema shape, not the data loss.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint('uq_quizzes_owner_url', 'quizzes', type_='unique')
    op.drop_index(op.f('ix_quizzes_owner_id'), table_name='quizzes')
    op.create_unique_constraint('uq_quizzes_url', 'quizzes', ['url'])
    op.drop_column('quizzes', 'owner_id')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_column('quiz_attempts', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
