"""support uploaded documents as a quiz source

Revision ID: 65401645c3de
Revises: 50bc66642d2b
Create Date: 2026-09-13 07:13:36.855336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65401645c3de'
down_revision: Union[str, Sequence[str], None] = '50bc66642d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('source_type', sa.String(), server_default='wikipedia', nullable=False))
    op.alter_column('quizzes', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('quizzes', 'source_type')
    # ### end Alembic commands ###
