"""configurable question count and difficulty

Revision ID: c122c9b4d795
Revises: 65401645c3de
Create Date: 2026-09-13 17:21:55.825161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c122c9b4d795'
down_revision: Union[str, Sequence[str], None] = '65401645c3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('question_count', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(), nullable=True))
    op.drop_constraint('uq_quizzes_owner_url', 'quizzes', type_='unique')
    op.create_unique_constraint('uq_quizzes_owner_url_params', 'quizzes', ['owner_id', 'url', 'question_count', 'difficulty'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quizzes_owner_url_params', 'quizzes', type_='unique')
    op.create_unique_constraint('uq_quizzes_owner_url', 'quizzes', ['owner_id', 'url'])
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('quizzes', 'question_count')
    # ### end Alembic commands ###
